'use client';

import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import type { VarianceExplanation } from '@/lib/variance/ai-explanations';

interface AIExplanationProps {
  explanation: VarianceExplanation;
  category: string;
}

const riskColors: Record<string, { bg: string; text: string }> = {
  low: { bg: 'bg-green-100 dark:bg-green-900', text: 'text-green-800 dark:text-green-200' },
  medium: { bg: 'bg-yellow-100 dark:bg-yellow-900', text: 'text-yellow-800 dark:text-yellow-200' },
  high: { bg: 'bg-red-100 dark:bg-red-900', text: 'text-red-800 dark:text-red-200' },
};

function formatCategory(category: string): string {
  return category
    .split('_')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}

export function AIExplanationCard({ explanation, category }: AIExplanationProps) {
  const risk = riskColors[explanation.risk_level] || riskColors.low;

  return (
    <Card className="border-l-4 border-l-primary">
      <CardHeader className="pb-3">
        <div className="flex items-center justify-between">
          <CardTitle className="text-sm">
            AI Analysis: {formatCategory(category)}
          </CardTitle>
          <Badge variant="outline" className={`${risk.bg} ${risk.text}`}>
            {explanation.risk_level} risk
          </Badge>
        </div>
      </CardHeader>
      <CardContent className="space-y-4">
        <p className="text-sm leading-relaxed">{explanation.explanation}</p>

        {explanation.action_items.length > 0 && (
          <div>
            <h4 className="mb-2 text-xs font-semibold uppercase tracking-wider text-muted-foreground">
              Recommended Actions
            </h4>
            <ul className="space-y-1">
              {explanation.action_items.map((action, i) => (
                <li key={i} className="flex items-start gap-2 text-sm">
                  <span className="mt-0.5 text-primary">
                    <svg className="h-3 w-3" fill="none" stroke="currentColor" viewBox="0 0 24 24" strokeWidth={2}>
                      <path strokeLinecap="round" strokeLinejoin="round" d="M9 5l7 7-7 7" />
                    </svg>
                  </span>
                  {action}
                </li>
              ))}
            </ul>
          </div>
        )}

        <p className="text-[10px] text-muted-foreground">
          Generated by AI based on your transaction data. Always verify with your advisor.
        </p>
      </CardContent>
    </Card>
  );
}
