import { NextResponse } from 'next/server';
import { getUserProfile } from '@/lib/auth/get-user-profile';
import { createUntypedServiceClient } from '@/lib/supabase/server';
import { logAudit } from '@/lib/audit/log';

// Seed Alonuko debt data from the Debt Overview spreadsheet
// This is a one-time operation to populate the debt command centre

const ALONUKO_FACILITIES = [
  // ============ BUSINESS LOANS ============
  {
    facility_name: 'Capital on Tap',
    lender: 'Capital on Tap',
    facility_type: 'credit_card' as const,
    classification: 'okay' as const,
    original_amount: 121585.56,
    current_balance: 51761.52,
    monthly_repayment: 5187,
    interest_rate: 0.0374,
    effective_apr: 0.55,
    start_date: '2022-11-15',
    maturity_date: null,
    repayment_frequency: 'monthly' as const,
    refinance_eligible: true,
    refinance_priority: 1,
    refinance_notes: 'High interest and high monthly repayment. Priority refinance target.',
    statement_access: 'james has login',
    notes: 'Maturity based on monthly repayment amount. Revolving credit facility.',
  },
  {
    facility_name: 'BBL (Bounce Back Loan)',
    lender: 'Lloyds',
    facility_type: 'government_loan' as const,
    classification: 'good' as const,
    original_amount: 37000,
    current_balance: 10407.24,
    monthly_repayment: 227,
    interest_rate: 0.079,
    effective_apr: 0.079,
    start_date: '2021-12-13',
    maturity_date: '2030-05-01',
    repayment_frequency: 'monthly' as const,
    refinance_eligible: false,
    notes: 'Recently extended from 48 months to 120 months. Interest added each month. Low cost, keep.',
  },
  {
    facility_name: 'Funding Circle (1)',
    lender: 'Funding Circle',
    facility_type: 'unsecured_loan' as const,
    classification: 'good' as const,
    original_amount: 55000,
    current_balance: 24516.44,
    monthly_repayment: 961,
    interest_rate: 0.079,
    start_date: '2022-08-23',
    maturity_date: '2028-07-01',
    repayment_frequency: 'monthly' as const,
    refinance_eligible: false,
    notes: '72 month term. Low interest, manageable repayment. Keep.',
    statement_access: 'james has login',
  },
  {
    facility_name: 'BizCap (FinCap)',
    lender: 'BizCap / FinCap',
    facility_type: 'unsecured_loan' as const,
    classification: 'bad' as const,
    original_amount: 64451,
    current_balance: 104300,
    monthly_repayment: 17171,
    interest_rate: 1.21,
    repayment_frequency: 'daily' as const,
    refinance_eligible: true,
    refinance_priority: 2,
    has_debenture: true,
    refinance_notes: 'Daily repayment of ~782.50 for 105 days. DEBENTURE. Effective 121% rate. Elect topup eligible.',
    notes: 'Pending includes previous loan balance. Extremely expensive.',
  },
  {
    facility_name: 'IWOCA',
    lender: 'IWOCA',
    facility_type: 'unsecured_loan' as const,
    classification: 'bad' as const,
    original_amount: 34000,
    current_balance: 15558.97,
    monthly_repayment: 2679,
    interest_rate: 0.0515,
    effective_apr: 0.82,
    start_date: '2024-11-20',
    maturity_date: '2026-12-01',
    payment_day: 18,
    repayment_frequency: 'monthly' as const,
    refinance_eligible: true,
    refinance_priority: 4,
    refinance_notes: '24 month loan - topup at 28k. High APR at 82%.',
    notes: 'Topup once balance drops below 28k.',
  },
  {
    facility_name: 'YouLend - Shopify',
    lender: 'YouLend',
    facility_type: 'mca' as const,
    classification: 'bad' as const,
    original_amount: 180000,
    current_balance: 79811.02,
    monthly_repayment: 0,
    interest_rate: 0,
    fixed_fee: 0.12,
    start_date: '2025-10-08',
    sweep_percentage: 17,
    sweep_source: 'shopify',
    repayment_frequency: 'when_paid' as const,
    refinance_eligible: false,
    refinance_notes: 'Repaying through income. Shopify may penalise for cash repayments. May topup to 250k.',
    notes: '17% sweep on all Shopify payments received. No stated APR but effective cost is very high.',
  },
  {
    facility_name: 'Elect - 112265',
    lender: 'Elect',
    facility_type: 'unsecured_loan' as const,
    classification: 'bad' as const,
    original_amount: 36071.28,
    current_balance: 180000,
    monthly_repayment: 31214,
    interest_rate: 1.24,
    repayment_frequency: 'daily' as const,
    refinance_eligible: true,
    refinance_priority: 3,
    refinance_notes: 'Daily repayment of ~1,357.14 for 90 days. 124% effective rate. Pending includes previous loan balance.',
    notes: 'New larger facility includes previous balance. Daily repayments extremely high.',
  },
  {
    facility_name: 'MCL Finance',
    lender: 'MCL Finance',
    facility_type: 'unsecured_loan' as const,
    classification: 'okay' as const,
    original_amount: 20004.30,
    current_balance: 20362.80,
    monthly_repayment: 2545,
    interest_rate: 0.072,
    effective_apr: 1.30,
    start_date: '2025-11-28',
    maturity_date: '2026-10-01',
    repayment_frequency: 'monthly' as const,
    notes: 'Monthly repayments for 12 months. Winds down by Oct 2026.',
  },
  {
    facility_name: 'Got Capital',
    lender: 'Got Capital',
    facility_type: 'unsecured_loan' as const,
    classification: 'bad' as const,
    original_amount: 6650,
    current_balance: 1750,
    monthly_repayment: 3500,
    interest_rate: 2.17,
    start_date: '2026-01-21',
    maturity_date: '2026-03-01',
    repayment_frequency: 'weekly' as const,
    status: 'paid_off' as const,
    refinance_notes: 'Weekly repayments of 875. 217% effective rate. Should be paid off by now.',
    notes: 'Weekly repayment of 875. Short-term expensive facility. Likely cleared.',
  },
  {
    facility_name: 'YouLend - Stripe',
    lender: 'YouLend',
    facility_type: 'mca' as const,
    classification: 'okay' as const,
    original_amount: 23400,
    current_balance: 26450.51,
    monthly_repayment: 0,
    interest_rate: 0.28,
    sweep_percentage: 18,
    sweep_source: 'stripe',
    repayment_frequency: 'when_paid' as const,
    notes: '18% sweep on Stripe payouts. 28% rate is lower than Shopify MCA.',
  },
  {
    facility_name: 'Swift Fund (Biz Lend) - New',
    lender: 'Swift Fund / Biz Lend',
    facility_type: 'unsecured_loan' as const,
    classification: 'bad' as const,
    original_amount: 30000,
    current_balance: 9200,
    monthly_repayment: 8800,
    interest_rate: 2.07,
    maturity_date: '2026-05-01',
    repayment_frequency: 'daily' as const,
    refinance_notes: 'Daily repayment between Mon-Fri, 400/day - 3 months. 207% effective rate.',
    notes: 'Previous Swift Fund loan paid off. This is the new facility. Nearly cleared.',
  },
  {
    facility_name: 'Funding Circle (2) - Nicole Secured',
    lender: 'Funding Circle',
    facility_type: 'secured_loan' as const,
    classification: 'okay' as const,
    original_amount: 100000,
    current_balance: 142706,
    monthly_repayment: 11892,
    interest_rate: 0.049,
    effective_apr: 0.75,
    start_date: '2026-04-09',
    maturity_date: '2027-03-01',
    secured: true,
    collateral_description: 'Nicole mortgage',
    repayment_frequency: 'monthly' as const,
    notes: 'Secured against Nicole mortgage. Monthly repayments for 12 months. Pending amount includes fees.',
  },
  // ============ DIRECTOR LOAN ACCOUNTS ============
  {
    facility_name: 'Gbemi Savings',
    lender: 'Gbemi (Director)',
    facility_type: 'director_loan' as const,
    classification: 'good' as const,
    original_amount: 15000,
    current_balance: 11700,
    monthly_repayment: 0,
    interest_rate: 0,
    repayment_frequency: 'none' as const,
    director_name: 'Gbemi',
    notes: 'Late Dec 2024 savings injection. Initially 15k, repaid 3.3k. No agreed interest or monthly repayments.',
  },
  {
    facility_name: 'Gbemi Loan (1) - Mid Feb',
    lender: 'Gbemi (Director) via Lloyds',
    facility_type: 'director_loan' as const,
    classification: 'okay' as const,
    original_amount: 25000,
    current_balance: 34000,
    monthly_repayment: 500,
    interest_rate: 0,
    director_name: 'Gbemi',
    repayment_frequency: 'monthly' as const,
    notes: 'Lloyds personal loan taken mid-Feb. DD 521.81/month, Alonuko pays Gbemi on 18th.',
  },
  {
    facility_name: 'Gbemi Loan (2) - Tesco & Lloyds',
    lender: 'Gbemi (Director) via Tesco/Lloyds',
    facility_type: 'director_loan' as const,
    classification: 'okay' as const,
    original_amount: 42000,
    current_balance: 42000,
    monthly_repayment: 800,
    interest_rate: 0,
    director_name: 'Gbemi',
    repayment_frequency: 'monthly' as const,
    notes: 'Late Jan. Paid 3 months of interest upfront - first payment 30th May.',
  },
  {
    facility_name: 'Gbemi - Everyday Loans',
    lender: 'Gbemi (Director) via Everyday Loans',
    facility_type: 'director_loan' as const,
    classification: 'okay' as const,
    original_amount: 10000,
    current_balance: 10000,
    monthly_repayment: 456.28,
    interest_rate: 0,
    director_name: 'Gbemi',
    payment_day: 1,
    repayment_frequency: 'monthly' as const,
    notes: 'Took 4 days to land. DD 456.28 on 1st, Alonuko pays on 28th.',
  },
  {
    facility_name: 'Gbemi - Virgin CC',
    lender: 'Gbemi (Director) via Virgin',
    facility_type: 'director_loan' as const,
    classification: 'okay' as const,
    original_amount: 6563.55,
    current_balance: 6563.55,
    monthly_repayment: 0,
    interest_rate: 0,
    director_name: 'Gbemi',
    payment_day: 6,
    repayment_frequency: 'monthly' as const,
    notes: 'Includes transfer fee. DD TBC on 6th, Alonuko pays on 28th.',
  },
  {
    facility_name: 'Gbemi - LISA',
    lender: 'Gbemi (Director) via LISA',
    facility_type: 'director_loan' as const,
    classification: 'good' as const,
    original_amount: 25813.60,
    current_balance: 25813.60,
    monthly_repayment: 0,
    interest_rate: 0,
    director_name: 'Gbemi',
    repayment_frequency: 'none' as const,
    notes: 'Received 19,749 (2 payments) but original was 25,813.60. No monthly repayment.',
  },
  {
    facility_name: 'Gbemi - Lloyds CC',
    lender: 'Gbemi (Director) via Lloyds CC',
    facility_type: 'director_loan' as const,
    classification: 'okay' as const,
    original_amount: 6500,
    current_balance: 6500,
    monthly_repayment: 29.28,
    interest_rate: 0,
    director_name: 'Gbemi',
    payment_day: 31,
    repayment_frequency: 'monthly' as const,
    notes: 'Current balance ~3,000. DD 29.28 on 31st, Alonuko pays 204.50 on 28th.',
  },
  {
    facility_name: 'Nicole Loan - Halifax',
    lender: 'Nicole (Director) via Halifax',
    facility_type: 'director_loan' as const,
    classification: 'okay' as const,
    original_amount: 25000,
    current_balance: 34592.88,
    monthly_repayment: 411.82,
    interest_rate: 0.0081,
    effective_apr: 0.102,
    maturity_date: '2032-02-01',
    director_name: 'Nicole',
    repayment_frequency: 'monthly' as const,
    notes: 'Late Jan - Halifax. Paid 6 months of interest upfront - first payment 30th May. Long maturity.',
  },
  {
    facility_name: 'James Loan - Lendable',
    lender: 'James (Director) via Lendable',
    facility_type: 'director_loan' as const,
    classification: 'okay' as const,
    original_amount: 28000,
    current_balance: 28000,
    monthly_repayment: 517.25,
    interest_rate: 0,
    director_name: 'James',
    repayment_frequency: 'monthly' as const,
    notes: 'Late Jan - Lendable. Paid 3 months of interest upfront - first payment 30th May.',
  },
  {
    facility_name: 'James Amex',
    lender: 'James (Director) via Amex',
    facility_type: 'director_loan' as const,
    classification: 'bad' as const,
    original_amount: 25000,
    current_balance: 25000,
    monthly_repayment: 5500,
    interest_rate: 0,
    director_name: 'James',
    repayment_frequency: 'monthly' as const,
    notes: 'Credit card. High monthly repayment obligation.',
  },
  {
    facility_name: 'Larry Loan',
    lender: 'Larry (External)',
    facility_type: 'director_loan' as const,
    classification: 'good' as const,
    original_amount: 50000,
    current_balance: 50000,
    monthly_repayment: 0,
    interest_rate: 0,
    director_name: 'Larry',
    repayment_frequency: 'none' as const,
    notes: 'Savings-based loan from Larry. No agreed interest or monthly repayments.',
  },
  {
    facility_name: 'Femi Kumyi Loan',
    lender: 'Femi Kumyi (External)',
    facility_type: 'director_loan' as const,
    classification: 'good' as const,
    original_amount: 10000,
    current_balance: 10000,
    monthly_repayment: 0,
    interest_rate: 0,
    director_name: 'Femi Kumyi',
    repayment_frequency: 'none' as const,
    notes: 'External loan. No monthly repayment agreed.',
  },
  // ============ CREDITOR PAYMENT PLANS ============
  {
    facility_name: 'Create Staff - Payment Plan',
    lender: 'Create (Staffing)',
    facility_type: 'creditor_plan' as const,
    classification: 'okay' as const,
    original_amount: 20504.56,
    current_balance: 20504.56,
    monthly_repayment: 8000,
    interest_rate: 0,
    start_date: '2026-03-27',
    maturity_date: '2026-06-12',
    repayment_frequency: 'bi_weekly' as const,
    notes: 'Production staff provider. Bi-weekly 4,000 payments. New staff hired during payment plan.',
  },
  {
    facility_name: 'KTC - Payment Plan',
    lender: 'KTC (Embroidery)',
    facility_type: 'creditor_plan' as const,
    classification: 'okay' as const,
    original_amount: 12037,
    current_balance: 12037,
    monthly_repayment: 8000,
    interest_rate: 0,
    start_date: '2026-03-30',
    maturity_date: '2026-04-27',
    repayment_frequency: 'bi_weekly' as const,
    notes: 'Embroidery provider. Bi-weekly 4,000 payments. Clears by end of April.',
  },
  {
    facility_name: 'Yousuf - Creditor',
    lender: 'Yousuf (Embroidery)',
    facility_type: 'creditor_plan' as const,
    classification: 'bad' as const,
    original_amount: 85000,
    current_balance: 85000,
    monthly_repayment: 0,
    interest_rate: 0,
    repayment_frequency: 'none' as const,
    notes: 'Embroidery provider. No repayment plan agreed yet. Large outstanding balance.',
  },
];

export async function POST() {
  try {
    const { orgId, userId } = await getUserProfile();
    const supabase = await createUntypedServiceClient();

    // Check if already seeded
    const { count } = await supabase
      .from('debt_facilities')
      .select('id', { count: 'exact', head: true })
      .eq('org_id', orgId);

    if ((count ?? 0) > 0) {
      return NextResponse.json({
        message: `Already seeded. ${count} facilities exist.`,
        seeded: false,
      });
    }

    // Insert all facilities
    const toInsert = ALONUKO_FACILITIES.map((f) => ({
      status: 'active' as const,
      ...f,
      org_id: orgId,
    }));

    const { data, error } = await supabase
      .from('debt_facilities')
      .insert(toInsert)
      .select('id, facility_name');

    if (error) {
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    await logAudit({
      orgId,
      userId,
      action: 'debt_facilities_seeded',
      entityType: 'debt_facility',
      entityId: orgId,
      changes: { count: data?.length, facilities: data?.map((d: Record<string, unknown>) => d.facility_name) },
    });

    return NextResponse.json({
      message: `Seeded ${data?.length} debt facilities`,
      seeded: true,
      facilities: data,
    }, { status: 201 });
  } catch {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }
}
