'use client';

import { useState } from 'react';

interface AIReasoningProps {
  /** The reasoning text or structured explanation */
  reasoning: string;
  /** Optional: what data sources were used */
  dataSources?: string[];
  /** Optional: confidence level */
  confidence?: 'high' | 'medium' | 'low';
  /** Optional: AI model used */
  modelId?: string;
  /** Optional: custom trigger label (defaults to "Why this result?") */
  triggerLabel?: string;
  /** Optional: additional class names for the wrapper */
  className?: string;
}

const confidenceConfig = {
  high: { label: 'High confidence', colour: 'bg-green-100 text-green-700' },
  medium: { label: 'Medium confidence', colour: 'bg-amber-100 text-amber-700' },
  low: { label: 'Low confidence', colour: 'bg-red-100 text-red-700' },
};

/**
 * Collapsible "Show reasoning" component for AI-generated outputs.
 * Platform-wide requirement: every AI insight must have an expandable
 * section showing what data was used, assumptions made, and how the
 * conclusion was reached.
 */
export function AIReasoning({
  reasoning,
  dataSources,
  confidence,
  modelId,
  triggerLabel = 'Why this result?',
  className = '',
}: AIReasoningProps) {
  const [expanded, setExpanded] = useState(false);

  if (!reasoning) return null;

  return (
    <div className={`mt-2 ${className}`}>
      <button
        type="button"
        onClick={() => setExpanded(!expanded)}
        className="flex items-center gap-1.5 text-xs text-gray-500 hover:text-gray-700 transition-colors group"
      >
        <svg
          className={`h-3.5 w-3.5 transition-transform ${expanded ? 'rotate-90' : ''}`}
          fill="none"
          stroke="currentColor"
          viewBox="0 0 24 24"
          strokeWidth={2}
        >
          <path strokeLinecap="round" strokeLinejoin="round" d="M9 5l7 7-7 7" />
        </svg>
        <span className="group-hover:underline">{triggerLabel}</span>
        {confidence && (
          <span className={`ml-1 px-1.5 py-0.5 rounded text-[10px] font-medium ${confidenceConfig[confidence].colour}`}>
            {confidenceConfig[confidence].label}
          </span>
        )}
      </button>

      {expanded && (
        <div className="mt-2 ml-5 space-y-2 rounded-lg border border-gray-200 bg-gray-50 p-3 text-xs text-gray-600 animate-in fade-in slide-in-from-top-1 duration-200">
          {/* Reasoning text */}
          <div>
            <h4 className="font-semibold text-gray-700 mb-1">Reasoning</h4>
            <p className="whitespace-pre-wrap leading-relaxed">{reasoning}</p>
          </div>

          {/* Data sources */}
          {dataSources && dataSources.length > 0 && (
            <div>
              <h4 className="font-semibold text-gray-700 mb-1">Data sources</h4>
              <ul className="list-disc list-inside space-y-0.5">
                {dataSources.map((source, i) => (
                  <li key={i}>{source}</li>
                ))}
              </ul>
            </div>
          )}

          {/* Model attribution */}
          {modelId && (
            <div className="flex items-center gap-1 pt-1 border-t border-gray-200 text-[10px] text-gray-400">
              <svg className="h-3 w-3" fill="none" stroke="currentColor" viewBox="0 0 24 24" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M9.75 3.104v5.714a2.25 2.25 0 01-.659 1.591L5 14.5M9.75 3.104c-.251.023-.501.05-.75.082m.75-.082a24.301 24.301 0 014.5 0m0 0v5.714c0 .597.237 1.17.659 1.591L19.8 15.3M14.25 3.104c.251.023.501.05.75.082M19.8 15.3l-1.57.393A9.065 9.065 0 0112 15a9.065 9.065 0 00-6.23.693L5 14.5m14.8.8l1.402 1.402c1.232 1.232.65 3.318-1.067 3.611A48.309 48.309 0 0112 21c-2.773 0-5.491-.235-8.135-.687-1.718-.293-2.3-2.379-1.067-3.61L5 14.5" />
              </svg>
              <span>Generated by {modelId}</span>
            </div>
          )}

          {/* Powered by Claude */}
          <div className="flex items-center gap-1 pt-1 border-t border-gray-200 text-[10px] text-gray-400">
            <svg className="h-3 w-3" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M9.813 15.904L9 18.75l-.813-2.846a4.5 4.5 0 00-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 003.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 003.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 00-3.09 3.09zM18.259 8.715L18 9.75l-.259-1.035a3.375 3.375 0 00-2.455-2.456L14.25 6l1.036-.259a3.375 3.375 0 002.455-2.456L18 2.25l.259 1.035a3.375 3.375 0 002.455 2.456L21.75 6l-1.036.259a3.375 3.375 0 00-2.455 2.456z" />
            </svg>
            <span>Powered by Claude</span>
          </div>
        </div>
      )}
    </div>
  );
}

/**
 * Confirmation dialog component for destructive or significant actions.
 * Use before mutations like delete, archive, or irreversible state changes.
 */
interface ConfirmDialogProps {
  open: boolean;
  title: string;
  description: string;
  confirmLabel?: string;
  cancelLabel?: string;
  variant?: 'danger' | 'warning' | 'default';
  onConfirm: () => void;
  onCancel: () => void;
}

const variantStyles = {
  danger: {
    button: 'bg-red-600 hover:bg-red-700 text-white',
    icon: 'text-red-600',
  },
  warning: {
    button: 'bg-amber-600 hover:bg-amber-700 text-white',
    icon: 'text-amber-600',
  },
  default: {
    button: 'bg-blue-600 hover:bg-blue-700 text-white',
    icon: 'text-blue-600',
  },
};

export function ConfirmDialog({
  open,
  title,
  description,
  confirmLabel = 'Confirm',
  cancelLabel = 'Cancel',
  variant = 'default',
  onConfirm,
  onCancel,
}: ConfirmDialogProps) {
  if (!open) return null;

  const styles = variantStyles[variant];

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center">
      {/* Backdrop */}
      <div className="absolute inset-0 bg-black/50" onClick={onCancel} />

      {/* Dialog */}
      <div className="relative bg-white rounded-xl shadow-xl max-w-md w-full mx-4 p-6 animate-in fade-in zoom-in-95 duration-200">
        <div className="flex items-start gap-4">
          <div className={`flex-shrink-0 rounded-full bg-gray-100 p-2 ${styles.icon}`}>
            <svg className="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126zM12 15.75h.007v.008H12v-.008z" />
            </svg>
          </div>
          <div className="flex-1">
            <h3 className="text-base font-semibold text-gray-900">{title}</h3>
            <p className="mt-1 text-sm text-gray-500">{description}</p>
          </div>
        </div>

        <div className="mt-6 flex justify-end gap-3">
          <button
            type="button"
            onClick={onCancel}
            className="rounded-lg border border-gray-300 px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 transition-colors"
          >
            {cancelLabel}
          </button>
          <button
            type="button"
            onClick={onConfirm}
            className={`rounded-lg px-4 py-2 text-sm font-medium transition-colors ${styles.button}`}
          >
            {confirmLabel}
          </button>
        </div>
      </div>
    </div>
  );
}
